name: Test Project 4

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Project 4
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_4 }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY_4 }}
        run: |
          curl -i \
            "$SUPABASE_URL/rest/v1/products?select=*" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY"
