name: Test Project 2

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Project 2
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_2 }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY_2 }}
        run: |
          curl -i \
            "$SUPABASE_URL/rest/v1/users?select=*" \
            -H "apikey: $SUPABASE_KEY" \
            -H "Authorization: Bearer $SUPABASE_KEY"
